### PR TITLE
Update to new rodakase

### PR DESCRIPTION
**Pull request by solnic**
:gift: :tada:

### CODE REVIEW

**Comment by timriley** [comment]
Wow, you're too kind! I'll take a look at this today/tomorrow and let you know if I have any questions :)

**Comment by solnic** [comment]
It's a test drive for my stuff so there's mutual benefit here ;)

Anyway, lemme know if you have questions. I don't like explicit copying of
options between containers but apart from that this seems like a nice setup.

I am, as you know, open to ideas how things can be improved. It uses
rodakase and dry-component from master but if we can get it to work it
would make sense to push releases :)

**Comment by timriley** [comment]
Thanks again, @solnic, this is great! The biggest issue I found was the one in dryrb/dry-component#2, everything else looks good to me.

I'd definitely like to avoid the copying of configs around the various containers. I wonder if I should just set up another shared container whose job it is to hold a common `Dry::Component::Config` object and then `import` that into all the sub-app containers who would want it? Seems cleaner to me?

**Comment by solnic** [comment]
@timriley yeah it feels like having config as a separate concept would make it more reusable

**Pull request merged**
